RefugeeApp/config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  root 'pages#home'

  resources :refugees
  resources :champions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RefugeeApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RefugeeApp/app/models/champion.rb
class Champion < ApplicationRecord
  has_secure_password
end

RefugeeApp/app/models/city.rb
class City < ApplicationRecord
end

RefugeeApp/app/models/refugee.rb
class Refugee < ApplicationRecord
  has_secure_password
end

RefugeeApp/app/models/state.rb
class State < ApplicationRecord
end

RefugeeApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

RefugeeApp/app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
  before_action :set_champion, only: [:show, :edit, :update, :destroy]

  # GET /champions
  # GET /champions.json
  def index
    @champions = Champion.all
  end

  # GET /champions/1
  # GET /champions/1.json
  def show
  end

  # GET /champions/new
  def new
    @champion = Champion.new
  end

  # GET /champions/1/edit
  def edit
  end

  # POST /champions
  # POST /champions.json
  def create
    @champion = Champion.new(champion_params)

    respond_to do |format|
      if @champion.save
        format.html { redirect_to @champion, notice: 'Champion was successfully created.' }
        format.json { render :show, status: :created, location: @champion }
      else
        format.html { render :new }
        format.json { render json: @champion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /champions/1
  # PATCH/PUT /champions/1.json
  def update
    respond_to do |format|
      if @champion.update(champion_params)
        format.html { redirect_to @champion, notice: 'Champion was successfully updated.' }
        format.json { render :show, status: :ok, location: @champion }
      else
        format.html { render :edit }
        format.json { render json: @champion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /champions/1
  # DELETE /champions/1.json
  def destroy
    @champion.destroy
    respond_to do |format|
      format.html { redirect_to champions_url, notice: 'Champion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_champion
      @champion = Champion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def champion_params
      params.require(:champion).permit(:name, :email, :origin, :language, :password, :password_confirmation, :phone)
    end
end

RefugeeApp/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

RefugeeApp/app/controllers/refugees_controller.rb
class RefugeesController < ApplicationController
  before_action :set_refugee, only: [:show, :edit, :update, :destroy]

  # GET /refugees
  # GET /refugees.json
  def index
    @refugees = Refugee.all
  end

  # GET /refugees/1
  # GET /refugees/1.json
  def show
  end

  # GET /refugees/new
  def new
    @refugee = Refugee.new
  end

  # GET /refugees/1/edit
  def edit
  end

  # POST /refugees
  # POST /refugees.json
  def create
    @refugee = Refugee.new(refugee_params)

    respond_to do |format|
      if @refugee.save
        format.html { redirect_to @refugee, notice: 'Refugee was successfully created.' }
        format.json { render :show, status: :created, location: @refugee }
      else
        format.html { render :new }
        format.json { render json: @refugee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /refugees/1
  # PATCH/PUT /refugees/1.json
  def update
    respond_to do |format|
      if @refugee.update(refugee_params)
        format.html { redirect_to @refugee, notice: 'Refugee was successfully updated.' }
        format.json { render :show, status: :ok, location: @refugee }
      else
        format.html { render :edit }
        format.json { render json: @refugee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /refugees/1
  # DELETE /refugees/1.json
  def destroy
    @refugee.destroy
    respond_to do |format|
      format.html { redirect_to refugees_url, notice: 'Refugee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_refugee
      @refugee = Refugee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def refugee_params
      params.require(:refugee).permit(:name, :email, :origin, :language, :problems, :password, :password_confirmation, :phone)
    end
end

RefugeeApp/app/helpers/application_helper.rb
module ApplicationHelper
end

RefugeeApp/app/helpers/champions_helper.rb
module ChampionsHelper
end

RefugeeApp/app/helpers/pages_helper.rb
module PagesHelper
end

RefugeeApp/app/helpers/refugees_helper.rb
module RefugeesHelper
end

RefugeeApp/app/views/champions/_form.html.erb
<%= form_with(model: champion, local: true) do |form| %>
  <% if champion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(champion.errors.count, "error") %> prohibited this champion from being saved:</h2>

      <ul>
      <% champion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :champion_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :champion_email %>
  </div>

  <div class="field">
    <%= form.label :origin %>
    <%= form.text_field :origin, id: :champion_origin %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language, id: :champion_language %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :champion_password_digest %>
  </div>

  <div class="field">
    <%= form.label :confirm_password %>
    <%= form.password_field :password, id: :champion_password_digest %>
  </div>

  <div class="field">
    <%= form.label :solved %>
    <%= form.text_area :solved %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

RefugeeApp/app/views/champions/edit.html.erb
<h1>Editing Champion</h1>

<%= render 'form', champion: @champion %>

<%= link_to 'Show', @champion %> |
<%= link_to 'Back', champions_path %>

RefugeeApp/app/views/champions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Champions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Origin</th>
      <th>Language</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @champions.each do |champion| %>
      <tr>
        <td><%= champion.name %></td>
        <td><%= champion.email %></td>
        <td><%= champion.origin %></td>
        <td><%= champion.language %></td>
        <td><%= champion.password_digest %></td>
        <td><%= link_to 'Show', champion %></td>
        <td><%= link_to 'Edit', edit_champion_path(champion) %></td>
        <td><%= link_to 'Destroy', champion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Champion', new_champion_path %>
<%= link_to 'Home', new_champion_path %>

RefugeeApp/app/views/champions/new.html.erb
<h1>New Champion</h1>

<%= render 'form', champion: @champion %>

<%= link_to 'Back', champions_path %>

RefugeeApp/app/views/champions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @champion.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @champion.email %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @champion.origin %>
</p>

<p>
  <strong>Language:</strong>
  <%= @champion.language %>
</p>



<%= link_to 'Edit', edit_champion_path(@champion) %> |
<%= link_to 'Back', Home_path %>

RefugeeApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RefugeeApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

RefugeeApp/app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

RefugeeApp/app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

RefugeeApp/app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
    <head>
    <title>Super epic awesome site</title>
<!--Creates a reference to a new file-->
<!--Creates a reference to a new file-->
<!--rel tells you what kind of thing it is - so CSS is a cascading style sheet and rel titles it a stylesheet-->
        <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body class="container">
      <div class="row">

        <div class="col-md-8">
         <h1>Welcome to America!</h1>
         <p>Choose Your Language:</p>
         <h3>
           <select>
              <option>English</option>
              <option>French</option>
              <option>Spanish</option>
            </select>
         </h3>
        <a href="<%= new_refugee_path %>" class="btn-general">SIGN UP</a>
        <a href="#" class="btn-general">SIGN IN</a>


        </div>
        <div class="col-md-4">
        <img src="https://media2.giphy.com/media/xT9DPyXuYqhFtmdTFu/giphy.gif" class="home-image">
        </div>
        </div>

    </body>
</html>

<!--Does visual studio have a live preview feature?-->
<!--How do I link an image - insert image into href-->
<!--Ctrl slash to comment things out-->
<!--Style is an attribute so it goes inside of the h tag-->
<!--Find better ways to do layouts instead of tables go talk to Spotify girl-->
<!--ids are attributes and don't show on same page - like style it goes inside of the tags-->
<!--Classes are used to group elements together when applying layouts etc-->
<!--Divs allow you to divide your page into sections-->
<!--Span formats things inline-->
<!--Only works with fonts you have downloaded on your computer-->

RefugeeApp/app/views/refugees/_form.html.erb
<%= form_with(model: refugee, local: true) do |form| %>
  <% if refugee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(refugee.errors.count, "error") %> prohibited this refugee from being saved:</h2>

      <ul>
      <% refugee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div style="text-align: center;">
  <div>
    <%= form.text_field :name, placeholder: 'Enter your name' %>
  </div>

  <div>
    <%= form.text_field :email, placeholder: 'Email address' %>
  </div>

  <div>
    <%= form.text_field :origin, placeholder: 'Where are you from?' %>
  </div>

  <div>
    <%= form.password_field :password, placeholder: 'Enter a password' %>
  </div>

  <div>
    <%= form.password_field :password, placeholder: 'Confirm your password' %>
  </div>

  <div>
    <%= form.text_field :problems, placeholder: 'Your needs' %>
  </div>

  <div>
    <%= form.text_field :phone, placeholder: 'Your phone number' %>

  <div class="actions">
    <%= form.submit 'create profile', class: 'btn-general', style:'text-align:center;' %>
  </div>
</div>
</div>
<% end %>

RefugeeApp/app/views/refugees/edit.html.erb
<h1>Editing Refugee</h1>

<%= render 'form', refugee: @refugee %>

<%= link_to 'Show', @refugee %> |
<%= link_to 'Back', refugees_path %>

RefugeeApp/app/views/refugees/index.html.erb
<h1>Refugees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Origin</th>
      <th>Language</th>
      <th>Problems</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @refugees.each do |refugee| %>
      <tr>
        <td><%= refugee.name %></td>
        <td><%= refugee.email %></td>
        <td><%= refugee.origin %></td>
        <td><%= refugee.language %></td>
        <td><%= refugee.problems %></td>
        <td><%= link_to 'Show', refugee %></td>
        <td><%= link_to 'Edit', edit_refugee_path(refugee) %></td>
        <td><%= link_to 'Destroy', refugee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Refugee', new_refugee_path %>

RefugeeApp/app/views/refugees/new.html.erb
<div style="text-align: center;">
<h1 class="form-title">Tell us more about you </h1>
</div>

<%= render 'form', refugee: @refugee %>

<%= link_to 'Back', refugees_path %>

RefugeeApp/app/views/refugees/show.html.erb
<p id="notice"><%= notice %></p>

<div style="text-align; center:">
  <h1> Searching for the best fit </h1>

<img src="http://media.giphy.com/media/Hp4lpOT1Ns60o/giphy.gif" >
</div>

<%= link_to 'Edit', edit_refugee_path(@refugee) %> |
<%= link_to 'Back', refugees_path %>